version: '3.6'
services:
  db:
    image: postgres:13.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-dev
    ports:
      - "3005:3005"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - db


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
